---
- hosts: all
  become: true
  tasks:



  - name: Update repository index
    apt:
      update_cache: yes
    when: ansible_distribution_version == "Ubuntu"

  - name: install apache2 and php packages on Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: Update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution_version == "CentOS8"

  - name: install apache and php  packages on CentOS8
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS8"

 
