---
- hosts: all
  become: true
  tasks:

  - name: Update Ubuntu Repository Index
    apt:
      update_cache: yes
    when: ansible_distribution_version == "Ubuntu"

  - name: Install Apache2 Package on Ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Add PHP Support For Apache on Ubuntu
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Update CentOS8 Repository Index
    dnf:
      update_cache: yes
    when: ansible_distribution_version == "CentOS8"

  - name: Install Apache Package on CentOS8
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS8"

  - name: Add PHP Support For Apache on CentOS8
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS8"
