---
- hosts: all
  become: true
  tasks:


  - name: Install Apache2 and PHP Packages On Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: Install Apache and PHP  Packages on CentOS8
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS8"

 
