---
- hosts: all
  become: true
  tasks:

  - name: Install updates on (CentOS)
    tags: always
    dnf:
      upgrade: dist
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
  
  - name: Install updates on (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: Web_Servers
  become: yes
  tasks: 

  - name: Install apache2 and php packages on Ubuntu Web-Servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start apache2 (Ubuntu)
    tags: apache,centos,httpd
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"


  - name: Install apache and php on CentOS Web-Servers
    tags: apache,centos,httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"


  - name: Copy custom html file for the Web-Server site
    tags: apache,apache2,httpd
    copy: 
      src: /home/server/Ansible_Tutorial/homepage/homepage.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: Start httpd service on (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: Change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebod@somebod.somewhere.com
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: Restart httpd on (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed


- hosts: db_Servers
  become: true
  tasks:
  - name: Install mariad package (CentOS)
    tags: centos,db,mariadb
    dnf: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install Mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: File_Servers
  become: true
  tasks:
  - name: Install Samba Package
    tags: samba
    package: 
      name: samba
      state: latest
